### PR TITLE
Add osx_arm64 build to the feedstock

### PR DESCRIPTION
**Pull request by sauravrt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sauravrt** [comment]
@conda-forge-admin, please rerender

**Comment by xoolive** [comment]
Hello @sauravrt, (cc @junzis) 
Thank you for your help in providing an osx_arm64 target. I am pretty irrelevant in that matter, so please drop a line here when you found your way through the errors and it's all ready to merge.

**Review by xoolive — COMMENTED** [review]
No specific remark for now

**Comment by sauravrt** [comment]
Hi @xoolive , all checks have passed after my latest fix. The PR is ready to merge. Please review. 
Let me know if any changes are needed.

**Comment by xoolive** [comment]
Wow, thanks @sauravrt, good job!

I see tests are deactivated for cross compilation (is that right?)
Do you know if there is any way to check the recipe loads well on osx_arm64?

I see many errors [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=419006&view=logs&j=1b8be447-c2bd-5772-b66a-a1146441bf88&t=0da7bde9-21e8-5d19-f418-738876121ca7&l=1503) and would feel reassured if there's some kind of proof that loading the package on this architecture worked as well.

**Comment by sauravrt** [comment]
> Wow, thanks @sauravrt, good job!
Thanks @xoolive . This is my first time working on condo builds. I'm learning as I work on this build for pymodes.
> 
> I see tests are deactivated for cross compilation (is that right?) Do you know if there is any way to check the recipe loads well on osx_arm64?
I have been following the guidelines provided at https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/. It does look like tests can be enabled for cross compilation too. I have tested this recipe on my M1 machine and it loads well. I don't know if this can be tested on the Azure pipelines.

> 
> I see many errors [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=419006&view=logs&j=1b8be447-c2bd-5772-b66a-a1146441bf88&t=0da7bde9-21e8-5d19-f418-738876121ca7&l=1503) and would feel reassured if there's some kind of proof that loading the package on this architecture worked as well.

I'll look into this.

**Comment by xoolive** [comment]
If it loads well, that's fine with me. Just have a look and say again when you're done. If you believe it's fine, I'll merge right away.

**Comment by sauravrt** [comment]
> If it loads well, that's fine with me. Just have a look for the sake of it and say again when you're done. If you believe it's fine, I'll merge it.

I did a local conda-build and was able to install pyModeS on my osx_arm64 platform. I am able to import `pyModeS` and run examples in https://mode-s.org. 

> 
> Oh and do you know why you need `pybind` and not `numpy` in cross compilation? Just curious...

I originally added `pybind` and `numpy` to the recipe following the guideline on [How to add osx_arm64 to feedstock](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock). Once I sent the PR, checks failed for Python 3.9 and 3.10 on osx_arm64 builds.  I noticed that the error was due to [mamba being unable to solve for numpy 1.16](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=418516&view=logs&j=1b8be447-c2bd-5772-b66a-a1146441bf88&t=0da7bde9-21e8-5d19-f418-738876121ca7&l=85).  Since numpy was not a build requirement in the recipe before, I decided to remove it and the checks passed.
I'm not sure about pybind11. The condo-forge's guideline is not very clear on this matter either.

**Comment by xoolive** [comment]
Many thanks for the detailed explanation!

**Pull request merged**
